export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_UNSUCCESS = "GET_POSTS_UNSUCCESS";
export const GET_POSTS = "GET_POSTS";
export const GET_COMMENTS = "GET_COMMENTS"
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
export const GET_COMMENTS_UNSUCCESS = "GET_COMMENTS_UNSUCCESS"
